- name: Auto Minify
  # You may pin to the exact commit or the version.
  # uses: nizarmah/auto-minify@f8323743bad5df5496e89eb086cb8aeb5e523866
  uses: nizarmah/auto-minify@v2.0
  with:
    # Directory that contains the files you want to minify. Defaults to current directory (.)
    directory: # optional, default is .
    # Directory that contains the minified files. Defaults to same directory
    output: # optional, default is 
    # Descend at most levels (a non-negative integer) levels of directories below the starting-points.
    maxdepth: # optional, default is 
    # Specifies which of the supported packages minifies JS files.
    js_engine: # optional, default is babel
